Feature/intro
frrenzy/balapanlar pull request #16
Opened 2022-08-16 17:43 UTC by anastasiian3

2022-08-17 00:15 UTC, frrenzy requested changes
почекай треды, пожалуйста, там есть вопросы и пожелания

2022-08-17 00:15 UTC, frrenzy commented on src/pages/index.css
> +@import '../blocks/button/_align/button_align_center.css';
файлик не нужен, как выяснилось

2022-08-17 00:15 UTC, frrenzy commented on src/index.html
> +            Каждый ребёнок талантлив по-своему. Наша цель&nbsp;&mdash; дать детям возможность раскрыть свои таланты, получить хорошие современные знания в&nbsp;ауле, и&nbsp;стать успешным и&nbsp;счас
давай тут строчку перенесем на новую после "раскрыть свои таланты", а то читать трудно

2022-08-17 00:15 UTC, frrenzy commented on src/index.html
> +          <div class="intro__info">
мне кажется, тут надо поправить выравнивание строк - </div> на одном уровне с <section>, например

2022-08-17 00:15 UTC, frrenzy commented on src/blocks/intro/intro.css
> +  height: 90vh;
высота должна быть 100vh-120px хедера, не? или 852 захардкодить, надо попробовать варики

2022-08-17 00:15 UTC, frrenzy commented on src/blocks/intro/intro.css
> +  background-image: url('../../images/intro_image.png');
размер картинки расходится с макетом: обрати внимание, что на макете не видно детей на дальнем ряду сидений перед сценой

2022-08-17 00:15 UTC, frrenzy commented on src/blocks/button/_align/button_align_center.css
> +}
файл не нужен, достаточно центровать все элементы родительского контейнера

2022-08-17 00:15 UTC, frrenzy commented on src/blocks/intro/__headline/intro__headline.css
> +  margin: 0.94em auto;
горизонтальный автомарджин не нужен, достаточно отцентровать все элементы родительского контейнера

2022-08-17 00:15 UTC, frrenzy commented on src/blocks/intro/__info/intro__info.css
> +}
по-моему, это все можно заменить на column, и не придется выравнивать автомарджинами или селф-элайнами заголовок и кнопку

2022-08-17 00:15 UTC, frrenzy commented on src/blocks/intro/__text/intro__text.css
> +  margin: 0 13.8em 0 0;
а тут почему такой специфический марджин?

2022-08-17 00:15 UTC, frrenzy commented on src/blocks/intro/intro.css
> +  flex-direction: column;
дублируются стили column, лучше отсюда удалить

2022-08-17 00:15 UTC, frrenzy commented on src/index.html
> +          >
тут как-то поехало все

2022-08-17 00:15 UTC, frrenzy commented on src/index.html
> +            >
и тут

2022-08-17 11:00 UTC, anastasiian3 commented on src/pages/index.css
> +@import '../blocks/button/_align/button_align_center.css';
+

2022-08-17 11:01 UTC, anastasiian3 commented on src/blocks/button/_align/button_align_center.css
> +}
долго сидела подгоняла, тупанула, спасибо за наводку

2022-08-17 11:01 UTC, anastasiian3 commented on src/index.html
> +            Каждый ребёнок талантлив по-своему. Наша цель&nbsp;&mdash; дать детям возможность раскрыть свои таланты, получить хорошие современные знания в&nbsp;ауле, и&nbsp;стать успешным и&nbsp;счас
+

2022-08-17 11:06 UTC, anastasiian3 commented on src/blocks/intro/intro.css
> +  height: 90vh;
захардкодила, иначе схлопывается

2022-08-17 11:10 UTC, anastasiian3 commented on src/blocks/intro/intro.css
> +  background-image: url('../../images/intro_image.png');
захардкодила и проблема для десктопа решилась, на мобилках буду отдельно смотреть

2022-08-17 11:12 UTC, anastasiian3 commented on src/blocks/intro/__headline/intro__headline.css
> +  margin: 0.94em auto;
++

2022-08-17 11:12 UTC, anastasiian3 commented on src/blocks/intro/__info/intro__info.css
> +}
++

2022-08-17 11:20 UTC, anastasiian3 commented on src/blocks/intro/__text/intro__text.css
> +  margin: 0 13.8em 0 0;
это я пыталась в адаптивку и упоролась, исправила

2022-08-17 11:21 UTC, anastasiian3 commented on src/blocks/intro/intro.css
> +  flex-direction: column;
++

2022-08-17 11:21 UTC, anastasiian3 commented on src/index.html
> +          >
++

2022-08-17 11:22 UTC, anastasiian3 commented on src/index.html
> +            >
++

2022-08-19 09:07 UTC, frrenzy commented on src/blocks/intro/__bar/intro__bar.css
> +    display: none;
ну как временная заглушка бусть будет пока

2022-08-19 09:07 UTC, frrenzy commented on src/blocks/intro/__text/intro__text.css
> +  /* margin: 0 330px 0 0; */
комменты лучше чистить наверн

2022-08-19 09:07 UTC, frrenzy commented on src/blocks/intro/__text/intro__text.css
> +    margin: 0;
а какой марджин заменяется в этом правиле? дефолтный?

2022-08-19 09:07 UTC, frrenzy commented on src/blocks/intro/intro.css
> +  /* height: 852px; */
тоже коммент

2022-08-19 09:07 UTC, frrenzy commented on src/index.html
> +        <section class="info">
вот сюда добавь page__element page__element_offset_xl для отступа от курсов

2022-08-19 09:07 UTC, frrenzy commented on src/index.html
> +        <section class="intro rounded column">
и тут page__element page__element_offset_xl для корректного отступа между блоками

2022-08-19 15:23 UTC, anastasiian3 commented
+ добавила адаптивку
+ убрала ненужные дивы
- осталось изменить фон на белый вверху картинки согласно макету (где закругление)

2022-08-19 17:55 UTC, frrenzy approved these changes
Уточни насчет 700 и 768 в правилах

2022-08-19 17:55 UTC, frrenzy commented on src/blocks/intro/__bar/intro__bar.css
> +@media screen and (max-width: 700px) {
вот насчет такой разницы в медиа-правилах уточни у Макса, пожалуйста

2022-08-19 17:57 UTC, merged