Feature/header
frrenzy/balapanlar pull request #17
Opened 2022-08-16 19:34 UTC by bronik04

2022-08-17 00:29 UTC, frrenzy requested changes
+ поменял ветку, в которую мерджим
+ ответь в треды ниже, пожалуйста

2022-08-17 00:29 UTC, frrenzy commented on src/blocks/content/content.css
> +}
верни пустую строку(

2022-08-17 00:29 UTC, frrenzy commented on src/blocks/header/__link/header__link.css
> +}
а ховер какой-нибудь? 

+ параметров из фигмы не хватает, текст-элайн и фонт-фичер-сеттингс, например

2022-08-17 00:29 UTC, frrenzy commented on src/blocks/header/__menu/header__menu.css
> +  list-style: none;
миксин list

2022-08-17 00:29 UTC, frrenzy commented on src/blocks/header/header.css
> +}
нужная пустая строка. тесты гоняешь?

2022-08-17 00:29 UTC, frrenzy commented on src/index.html
>  </head>
а верни как было плз + тайтл напиши, пожалуйста, все забываю

2022-08-17 00:29 UTC, frrenzy commented on src/index.html
> +          курсы</a>
в 1 строку не варик?)

2022-08-17 00:29 UTC, frrenzy commented on src/index.html
> +            <a href="#" class="header__link">Наши курсы</a>
а добавь как закончим сюда валидные ссылки на куски сайта, таску создам. вроде через айдишники у секций делается

2022-08-17 00:29 UTC, frrenzy commented on src/index.html
> -                <a href="#" class="button button_color_black button_size_m">Записаться</a>
тут дальше мильен изменений, что тут в 2 словах происходит?

2022-08-17 00:29 UTC, frrenzy commented on src/index.html
> +</html>
пустая строка нужна

2022-08-17 00:29 UTC, frrenzy commented on src/pages/index.css
> +
закинь под коммент блоки просто в начало кучки

2022-08-17 05:43 UTC, bronik04 commented on src/blocks/header/header.css
> +}
вчера вечером видимо туго соображал, забыл тест перед комитом сделать, сейчас все исправлю

2022-08-17 05:49 UTC, bronik04 commented on src/blocks/content/content.css
> +}
готово

2022-08-17 05:59 UTC, bronik04 commented on src/blocks/header/__link/header__link.css
> +}
готово

2022-08-17 06:00 UTC, bronik04 commented on src/blocks/content/content.css
> +}
форматер по умолчанию убирал, больше не должно такого быть

2022-08-17 06:09 UTC, bronik04 commented on src/index.html
> +          курсы</a>
претиер меня убивает

2022-08-17 06:11 UTC, bronik04 commented on src/index.html
> -                <a href="#" class="button button_color_black button_size_m">Записаться</a>
я вообще эти куски кода не трогал(  после мержа видимо опять претиер решил поправить как ему удобно

2022-08-17 06:11 UTC, bronik04 commented on src/index.html
> +</html>
сделал

2022-08-17 06:35 UTC, bronik04 commented on src/pages/index.css
> +
готово

2022-08-17 07:26 UTC, bronik04 commented on src/index.html
> +            <a href="#" class="header__link">Наши курсы</a>
Как страница будет, сделаю

2022-08-17 07:33 UTC, bronik04 commented on src/index.html
>  </head>
Тайтл добавил, с выравниванием проблемы(

2022-08-17 11:59 UTC, frrenzy reviewed
мелочи остались

2022-08-17 11:59 UTC, frrenzy commented on src/index.html
> +    <header class="header">
в телеге договорились вынести из контента

2022-08-17 11:59 UTC, frrenzy commented on src/blocks/header/__link/header__link.css
> +  cursor: pointer;
а вроде все еще не хватает параметров текста

2022-08-18 03:53 UTC, frrenzy requested changes
все незарезолвленные треды, в том числе выше

2022-08-18 03:53 UTC, frrenzy commented on src/blocks/logo/logo.css
> +  padding-right: 122px;
готов поставить жопу, что тут должно быть 120px, как в ui kit

2022-08-18 03:53 UTC, frrenzy commented on src/blocks/header/header.css
> +  left: 0;
sticky все-таки должен быть, иначе он выдирается из потока и перекрывает контент дальше. Top 0 оставить

2022-08-18 03:53 UTC, frrenzy commented on src/blocks/logo/logo.css
> +  padding-right: 122px;
а это давай в 1 строку объединим

2022-08-18 03:53 UTC, frrenzy commented on src/index.html
> +        <nav class="header__nav">
удали div.content все-таки, и верни курсы. Мне кажется ты именно из-за их отсутствия мог пропустить тот факт. что хедер сейчас перекрывает контент сразу при первоначальной загрузке
<img width="902" alt="Screenshot 2022-08-18 at 06 51 48" src="https://user-images.githubusercontent.com/90396571/185289601-431f4823-7025-4750-905e-67c3f420c06c.png">
<img width="902" alt="Screenshot 2022-08-18 at 06 52 25" src="https://user-images.githubusercontent.com/90396571/185289687-28965f05-0d26-43eb-a011-95ae17bd3c1e.png">

2022-08-18 03:53 UTC, frrenzy commented on src/index.html
> +        <nav class="header__nav">
сверху фиксд, снизу стики

2022-08-18 06:01 UTC, bronik04 commented on src/index.html
> +    <header class="header">
Готово

2022-08-18 06:04 UTC, bronik04 commented on src/blocks/header/__link/header__link.css
> +  cursor: pointer;
Добавил

2022-08-18 06:16 UTC, bronik04 commented on src/blocks/logo/logo.css
> +  padding-right: 122px;
Исправил

2022-08-18 06:16 UTC, bronik04 commented on src/blocks/header/header.css
> +  left: 0;
Вернул стики

2022-08-18 06:16 UTC, bronik04 commented on src/blocks/logo/logo.css
> +  padding-right: 122px;
Готово

2022-08-18 06:23 UTC, bronik04 commented on src/index.html
> +        <nav class="header__nav">
Контент убрал, курсы добовлять не стал, потестил на лореме, все норм 
![Снимок экрана 2022-08-18 в 09 20 58](https://user-images.githubusercontent.com/100709407/185308577-0036c57e-d528-48aa-9396-cfebc49685cf.png)

2022-08-18 11:12 UTC, frrenzy approved these changes
lgtm

2022-08-18 11:14 UTC, merged