feature(about): add about section
frrenzy/balapanlar pull request #18
Opened 2022-08-17 10:33 UTC by KirillKamratov

2022-08-17 12:26 UTC, frrenzy requested changes
треды

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/about/__element-wrapper/about__element-wrapper.css
> +  left: auto;
удали, если не нужно сдвигать с места релатив блок

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/about/__element/about__element.css
> +  flex-direction: column;
вот эти стили дублируют column. я бы написал в верстке `class="about__element column",  а тут внутри стилей  - `align-items: flex-start`, раз нужно такое выравнивание

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/about/__image-line/about__image-line.css
> +  left: 0;
а может задать эту линию как бэкграунд-имидж для текста на картинке?

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/about/__image-title/_white/about__image-title_white.css
> +}
должно быть about__image-title_color_white, мне кажется

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/about/__image-title/about__image-title.css
> +  color: #1e1e1e;
ну и тут тогшда цвет вынеси в модификатор about__image-title_color_black какой-нибудь

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/about/__image/about__image.css
> +  width: 594px;
595 вроде

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/about/__list/about__list.css
> +  width: calc(100% - 122px);
так как выравниваем отступы, тут должно быть 100%

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/about/__sublist-element/about__sublist-element.css
> +  flex-direction: row;
дефолтное значение, можно не писать

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/about/about.css
> +  flex-direction: column;
аналогично, колумн, а тут указать элайн

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/content/_wrapper/content_wrapper.css
> +.content__element_wrapper {
эти стили нигде не используются вроде? удоли, если так

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/list/_type/list_type_checked.css
> +  width: 24px;
ширина и высота всего списка 24 пикселся??

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/list/_type/list_type_checked.css
> +  height: 24px;
ширина и высота всего списка 24 пикселся??

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/wrapper/wrapper.css
> +  padding: 120px 0 0 120px;
я чет не понрял этого флекса с тем, что тут левый паддинг только, а у контента справа пустое место. давай тут просто padding 120 120 0, и поправитб ширину секции как выше

2022-08-17 12:26 UTC, frrenzy commented on src/blocks/about/about.css
> +  width: 100%;
добавь maw1200

2022-08-17 12:26 UTC, frrenzy commented on src/index.html
> +            <div class="about__element-wrapper rounded">
давай тут артикл, а не див

2022-08-17 12:26 UTC, frrenzy commented on src/index.html
> +              >
а эту картинку как bgi для about__image-title

2022-08-17 12:26 UTC, frrenzy commented on src/index.html
> +              <h2 class="about__image-title">
тут h3 - h2 уже есть

2022-08-17 12:26 UTC, frrenzy commented on src/index.html
> +                </p>
ты уже указал картинку через bgi, удали тогда img и подвинь текст в нужное место паддингом

2022-08-17 12:26 UTC, frrenzy commented on src/index.html
> +              <h2 class="about__image-title about__image-title_white">
h3

2022-08-17 13:05 UTC, KirillKamratov commented on src/blocks/about/__image-line/about__image-line.css
> +  left: 0;
не получается. у текста позиционирование 30 30. у фона 0 0.

2022-08-17 13:14 UTC, KirillKamratov commented on src/blocks/about/__element-wrapper/about__element-wrapper.css
> +  left: auto;
Ок, ты вроде говорил когда-то(мб путаю) что нужно ставить в любом случае.

2022-08-17 13:18 UTC, KirillKamratov commented on src/blocks/about/__element/about__element.css
> +  flex-direction: column;
done

2022-08-17 13:21 UTC, KirillKamratov commented on src/blocks/about/__image-title/_white/about__image-title_white.css
> +}
done

2022-08-17 13:26 UTC, KirillKamratov commented on src/blocks/about/__image-title/about__image-title.css
> +  color: #1e1e1e;
чуть по другому сделал. вынес только цвет

2022-08-17 13:27 UTC, KirillKamratov commented on src/blocks/about/__image/about__image.css
> +  width: 594px;
у одной 594
у другой 595
Как быть?)

2022-08-17 13:27 UTC, KirillKamratov commented on src/blocks/about/__list/about__list.css
> +  width: calc(100% - 122px);
done

2022-08-17 13:28 UTC, KirillKamratov commented on src/blocks/about/__sublist-element/about__sublist-element.css
> +  flex-direction: row;
Сам говорил, лучше указывать явно, чтобы не запутаться)

2022-08-17 13:30 UTC, KirillKamratov commented on src/blocks/about/about.css
> +  flex-direction: column;
done

2022-08-17 13:53 UTC, KirillKamratov commented on src/index.html
> +              <h2 class="about__image-title">
их же может быть несколько, нет? h1 только 1

2022-08-17 13:54 UTC, KirillKamratov commented on src/index.html
> +              <h2 class="about__image-title about__image-title_white">
done

2022-08-17 13:54 UTC, KirillKamratov commented on src/index.html
> +              <h2 class="about__image-title">
done

2022-08-17 14:09 UTC, KirillKamratov commented on src/index.html
> +                </p>
сделал иначе, похоже на те списки, которые есть выше

2022-08-17 14:10 UTC, KirillKamratov commented on src/blocks/about/__image-line/about__image-line.css
> +  left: 0;
+это нужно в таком случае прямо модификатор для оранжевой и желтой создавать. зачем? не лучше бы универсально оставить. Картинку поменял и в все

2022-08-17 14:10 UTC, KirillKamratov commented on src/blocks/content/_wrapper/content_wrapper.css
> +.content__element_wrapper {
done

2022-08-17 14:11 UTC, KirillKamratov commented on src/blocks/list/_type/list_type_checked.css
> +  width: 24px;
удалил

2022-08-17 14:12 UTC, KirillKamratov commented on src/blocks/list/_type/list_type_checked.css
> +  height: 24px;
удалил

2022-08-17 14:12 UTC, KirillKamratov commented on src/blocks/wrapper/wrapper.css
> +  padding: 120px 0 0 120px;
первую часть сделал. вторую не понял. Ширину секции как выше - где выше?

2022-08-17 14:12 UTC, KirillKamratov commented on src/blocks/about/about.css
> +  width: 100%;
что?

2022-08-17 14:12 UTC, frrenzy commented on src/blocks/about/__element-wrapper/about__element-wrapper.css
> +  left: auto;
если и ставить, то нолики - чтобы не подвинуть его как раз

2022-08-17 14:13 UTC, KirillKamratov commented on src/blocks/about/about.css
> +  width: 100%;
done

2022-08-17 14:13 UTC, frrenzy commented on src/blocks/about/__image-line/about__image-line.css
> +  left: 0;
семантически имг для линии - плохо

как реализоваать - bgp 0 end, текст внутри подвинуть паддингами

2022-08-17 14:15 UTC, frrenzy commented on src/blocks/about/__image/about__image.css
> +  width: 594px;
595

2022-08-17 14:15 UTC, KirillKamratov commented on src/index.html
> +            <div class="about__element-wrapper rounded">
done

2022-08-17 14:16 UTC, KirillKamratov commented on src/index.html
> +              >
сделал иначе, аналогично спискам выше

2022-08-17 14:16 UTC, frrenzy commented on src/index.html
> +              <h2 class="about__image-title">
ну если h2 ставить, то иерархия нарушается. h2 для заголовков секций

2022-08-17 14:17 UTC, KirillKamratov commented on src/index.html
> +                </p>
сделал иначе, аналогично спискам выше

2022-08-17 14:17 UTC, frrenzy commented on src/blocks/wrapper/wrapper.css
> +  padding: 120px 0 0 120px;
abot__list, уже сделад

2022-08-17 14:20 UTC, KirillKamratov commented on src/blocks/about/__element-wrapper/about__element-wrapper.css
> +  left: auto;
в любом случае - удалил

2022-08-17 14:20 UTC, KirillKamratov commented on src/blocks/about/__image/about__image.css
> +  width: 594px;
done

2022-08-17 14:21 UTC, KirillKamratov commented on src/index.html
> +              <h2 class="about__image-title">
в любом случае, поправил

2022-08-17 14:25 UTC, frrenzy requested changes
треды. выше тоже ответил на некоторые

2022-08-17 14:25 UTC, frrenzy commented on src/blocks/about/__element/about__element.css
> +  flex-direction: column;
ну раз дублируют, их стоит удалить

2022-08-17 14:25 UTC, frrenzy commented on src/blocks/about/about.css
> +  flex-direction: column;
повторяющиеся стили удали

2022-08-17 14:25 UTC, frrenzy commented on src/blocks/content/_wrapper/content_wrapper.css
> +.content__element_wrapper {
файл не удален

2022-08-17 14:25 UTC, frrenzy commented on src/blocks/list/_type/list_type_checked.css
> +  height: 24px;
не вижу, что удалены. закоммитил это изменение?

2022-08-17 14:25 UTC, frrenzy commented on src/index.html
> +              >
не, давай как бэкграунд
bgp 0 end
текст выровнять паддингами

2022-08-17 14:25 UTC, frrenzy commented on src/index.html
> +        </h3>
подзаголовки параграфами размечаем

2022-08-17 14:25 UTC, frrenzy commented on src/index.html
> +                     class="about__sublist-pic-checked">
ну да, тут тоже картинки надо как фон. посмотри на list_type_checked

2022-08-17 14:29 UTC, frrenzy commented on src/index.html
> +                </p>
не, фоном надо

2022-08-17 14:30 UTC, frrenzy commented on src/index.html
> +                     class="about__sublist-pic-checked">
геотега тоже касается

2022-08-17 15:19 UTC, KirillKamratov commented on src/blocks/about/__element/about__element.css
> +  flex-direction: column;
done

2022-08-17 15:24 UTC, KirillKamratov commented on src/blocks/content/_wrapper/content_wrapper.css
> +.content__element_wrapper {
done

2022-08-17 15:25 UTC, KirillKamratov commented on src/blocks/list/_type/list_type_checked.css
> +  height: 24px;
done

2022-08-17 15:25 UTC, KirillKamratov commented on src/blocks/list/_type/list_type_checked.css
> +  height: 24px;
пока не закоммитил, сначала отвечаю, потом коммичу

2022-08-17 19:38 UTC, KirillKamratov commented on src/blocks/about/__image-line/about__image-line.css
> +  left: 0;
вроде сделал с помощью еще одного дива. откомментируй пж

2022-08-17 19:38 UTC, KirillKamratov commented on src/index.html
> +        </h3>
done

2022-08-17 19:38 UTC, KirillKamratov commented on src/index.html
> +                     class="about__sublist-pic-checked">
done

2022-08-19 08:17 UTC, frrenzy reviewed
Почти готово, осталось причесать

2022-08-19 08:17 UTC, frrenzy commented on src/pages/index.css
> +@import '../blocks/list/__item/_type/list__item_type_crossed.css';
нетт импорта над ними самого list__item

2022-08-19 08:17 UTC, frrenzy commented on src/index.html
> +              </li>
текст в лишках скорее всего стоит обернуть в p.paragraph, из классов li удалить paragraph.
проверьь потом, что ничего не уехало

2022-08-19 08:17 UTC, frrenzy commented on src/index.html
> +            <ul class="about__sublist list">
давай саблист во чтот-то более осмысленное переименуем, типа about__features, а саблист айтем - в about__feature

Не забудь также переименовать сами файлы/папки и селекторы в этих файлах

2022-08-19 08:17 UTC, frrenzy commented on src/index.html
> +              <li class="about__sublist-element paragraph list__item_type_checked">
не хватает list__item для использования его модификатора

2022-08-19 08:17 UTC, frrenzy commented on src/index.html
> +      <section class="about column  page__element_offset_l">
не хватает page__element

2022-08-19 08:17 UTC, frrenzy commented on src/index.html
> +    <div class="wrapper content_wrapper rounded column">
удоли content_wrapper, и папку blocks/page/_wrapper

2022-08-19 08:17 UTC, frrenzy commented on src/blocks/list/__item/list__item.css
> +  display: none;
перенеси сюда все стили из list__item_type_checked, кроме картинки. Картинку зададим модификатором - галочку или крестик

2022-08-19 08:17 UTC, frrenzy commented on src/blocks/list/__item/_type/list__item_type_crossed.css
> +.list_type_crossed {
селектор надо поменять на list__item_type_crossed

2022-08-19 08:17 UTC, frrenzy commented on src/blocks/list/__item/_type/list__item_type_checked.css
> +  background-size: 24px 24px;
все эти стили, кроме bgi, перенеси в list__item, тогда юудем модификатором задавать только картинку - галочку или крестик

2022-08-19 08:17 UTC, frrenzy commented on src/blocks/about/__title/about__title.css
> +  margin: 0 0 40px 0;
тут можно просто 0 0 40px

2022-08-19 08:17 UTC, frrenzy commented on src/blocks/about/__subtitle/about__subtitle.css
> +  margin: 0 0 60px 0;
тут можно просто 0 0 60px

2022-08-19 08:17 UTC, frrenzy commented on src/blocks/about/__sublist/about__sublist.css
> +  flex-direction: column;
удали эти стили, они дублируют column, и добавь колумн, если его нет в списке классов тега

2022-08-19 08:17 UTC, frrenzy commented on src/blocks/about/__image-title/about__image-title.css
> +  left: 30px;
а без абсолюта ее задать нельзя? это же тупо блок текста в диве, просто флексом и паддингами его выровнять можно. как в рашн тревеле, там текст выровнян просто флексом

2022-08-19 08:38 UTC, KirillKamratov commented on src/pages/index.css
> +@import '../blocks/list/__item/_type/list__item_type_crossed.css';
+

2022-08-19 09:07 UTC, KirillKamratov commented on src/index.html
> +              </li>
+

2022-08-19 09:07 UTC, KirillKamratov commented on src/index.html
> +              <li class="about__sublist-element paragraph list__item_type_checked">
+

2022-08-19 09:08 UTC, KirillKamratov commented on src/index.html
> +      <section class="about column  page__element_offset_l">
+

2022-08-19 09:14 UTC, KirillKamratov commented on src/blocks/list/__item/_type/list__item_type_checked.css
> +  background-size: 24px 24px;
+

2022-08-19 09:15 UTC, KirillKamratov commented on src/index.html
> +    <div class="wrapper content_wrapper rounded column">
+

2022-08-19 09:16 UTC, KirillKamratov commented on src/blocks/list/__item/list__item.css
> +  display: none;
+

2022-08-19 09:16 UTC, KirillKamratov commented on src/blocks/list/__item/_type/list__item_type_crossed.css
> +.list_type_crossed {
+

2022-08-19 09:17 UTC, KirillKamratov commented on src/blocks/about/__title/about__title.css
> +  margin: 0 0 40px 0;
+

2022-08-19 09:18 UTC, KirillKamratov commented on src/blocks/about/__subtitle/about__subtitle.css
> +  margin: 0 0 60px 0;
+

2022-08-19 09:20 UTC, KirillKamratov commented on src/blocks/about/__sublist/about__sublist.css
> +  flex-direction: column;
+

2022-08-19 09:25 UTC, KirillKamratov commented on src/blocks/about/__image-title/about__image-title.css
> +  left: 30px;
+

2022-08-19 09:50 UTC, frrenzy reviewed
1 тред остался

2022-08-19 10:10 UTC, frrenzy approved these changes
lgtm

2022-08-19 10:11 UTC, merged