Feature/principles
frrenzy/balapanlar pull request #23
Opened 2022-08-17 19:01 UTC by anastasiian3

адаптивка, в принципе, готова

2022-08-18 03:36 UTC, frrenzy requested changes
треды

2022-08-18 03:36 UTC, frrenzy commented on src/blocks/principles/__list/principles__list.css
> +  list-style: none;
давай эти стили на микс list заменим

2022-08-18 03:36 UTC, frrenzy commented on src/blocks/principles/__item/principles__item.css
> +  align-items: center;
давай эти стили на микс column заменим

2022-08-18 03:36 UTC, frrenzy commented on src/index.html
> +          <img src="<%=require('./images/principles-1.png')%>" alt="Фото для иллюстрации" class="principles__image principles__image_size_m">
ужми картинки в жипег, если они еще не оптимизированы

2022-08-18 03:36 UTC, frrenzy commented on src/index.html
> +        <li class="principles__item">
этот элемент не виден на странице

2022-08-18 03:36 UTC, frrenzy commented on src/index.html
> +    <section class="principles rounded">
высота секции не по макету

2022-08-18 08:24 UTC, anastasiian3 commented on src/blocks/principles/__list/principles__list.css
> +  list-style: none;
++

2022-08-18 08:31 UTC, anastasiian3 commented on src/blocks/principles/__item/principles__item.css
> +  align-items: center;
попробовала, у айтема осталась минимальная ширина. видимо из-за того, что ширина идет выше свойств флекса, содержимое не центруется, оставлю без микса column
![image](https://user-images.githubusercontent.com/102759284/185348804-5d6041c0-5525-4f35-993e-8a7af0abb360.png)

2022-08-18 08:37 UTC, anastasiian3 commented on src/index.html
> +          <img src="<%=require('./images/principles-1.png')%>" alt="Фото для иллюстрации" class="principles__image principles__image_size_m">
оптимизировала, на жпеге появляются белые рамки

2022-08-18 15:18 UTC, anastasiian3 commented on src/index.html
> +        <li class="principles__item">
поизучала пример, который дан на макете, переделала ширину - у каждого элемента по 100%, у ul родителя авто. если дичь, буду дальше думать.

2022-08-18 15:23 UTC, anastasiian3 commented on src/index.html
> +    <section class="principles rounded">
высоту поменяла, из-за измененной ширины элементы теперь вплотную друг к другу, текст сместился, чтобы уместиться на странице. возможно, следует попробовать добавить этот эффект с горизонтальным скроллом, чтобы понять, в том ли направлении я двигаюсь

2022-08-23 09:32 UTC, frrenzy commented
@anastasiian3 твои стили не трогал особо, из изменений:
- перенес ширину в 3 экрана в список
- секции поставил ширину в 1 экран и добавил скрытие переполнения - это дало скругление со всех сторон
- добавил секции минимальную высоту в 1000 по макету
- добавил секции селф-элайн, чтобы не убирать column у мейна. По сути там проблема была в том, что список центровался на экране, а если его прибить не к центру, а к левому краю - то все ок

2022-08-23 09:35 UTC, frrenzy commented
Товарищ ревьюер, дропните лоремы после принципов своим коммитом - они нужны только чтобы показать, что анимация корректно завершается

2022-08-23 20:32 UTC, frrenzy approved these changes
LGTM

2022-08-23 20:32 UTC, merged