Feature/popups
frrenzy/balapanlar pull request #39
Opened 2022-08-20 14:45 UTC by ivanfonin

Я по началу старый макет смотрел, сообразил где-то на середине пути)) Добавил в общем стили для попапа курса и попапа партнёра. Чтобы открыть попап, нужно добавить класс _popup_opened_. Но так у других блоков мобильной вёрстки нет, чтобы посмотреть корректно попапы удобнее всего в инспекторе элементам _header_ и _main_ задать `display: none;`.

2022-08-20 16:38 UTC, frrenzy requested changes
с макетом всякие отступы не сходятся

2022-08-20 16:38 UTC, frrenzy commented on src/blocks/popup/__container/popup__container.css
>    padding: 25px 22px;
по макету тут паддинги по 15 в курсах
<img width="404" alt="Screenshot 2022-08-20 at 18 45 14" src="https://user-images.githubusercontent.com/90396571/185755384-ef42d4d4-ac73-4ddd-8a1c-3ed8eacd2340.png">
<img width="404" alt="Screenshot 2022-08-20 at 18 46 15" src="https://user-images.githubusercontent.com/90396571/185755386-9142f380-1291-436b-b69e-b47821d26885.png">
<img width="404" alt="Screenshot 2022-08-20 at 18 46 23" src="https://user-images.githubusercontent.com/90396571/185755387-1584d50e-733e-403f-b425-1982be314f6e.png">
 
 и по 10 в партнерах

2022-08-20 16:38 UTC, frrenzy commented on src/blocks/popup/__container/popup__container.css
>      padding: 34px 36px 37px 36px;
на десктопе по 30 в курсах
<img width="124" alt="Screenshot 2022-08-20 at 18 49 16" src="https://user-images.githubusercontent.com/90396571/185755504-9cacb6e1-bec9-417d-a0aa-4b6862bdbfe7.png">
<img width="190" alt="Screenshot 2022-08-20 at 18 49 46" src="https://user-images.githubusercontent.com/90396571/185755505-d7c21962-7a8b-445a-8497-5af6189332f1.png">
<img width="190" alt="Screenshot 2022-08-20 at 18 49 55" src="https://user-images.githubusercontent.com/90396571/185755506-f836282c-4fc3-4fcf-8bc7-b12fdddeaba6.png">

и по 40 в партнерах

2022-08-20 16:38 UTC, frrenzy commented on src/blocks/popup/__close/popup__close.css
> +    right: 45px;
тут по макету 35 35
<img width="190" alt="Screenshot 2022-08-20 at 19 01 48" src="https://user-images.githubusercontent.com/90396571/185755949-272a4a8a-7ce7-416f-8598-d0054942e4b4.png">

2022-08-20 16:38 UTC, frrenzy commented on src/blocks/popup/__close/popup__close.css
> +  right: 0;
тут по макету -35 5, если мои расчеты верны
<img width="190" alt="Screenshot 2022-08-20 at 19 03 45" src="https://user-images.githubusercontent.com/90396571/185755972-a7cfdab2-645a-4d8a-864a-9c2044571a5d.png">

2022-08-20 16:38 UTC, frrenzy commented on src/blocks/popup/__buttons/popup__buttons.css
> +    align-items: center;
я полагаю, на макете "смотреть все" вместо "закрыьт", но порядок другой. column-reverse?
<img width="190" alt="Screenshot 2022-08-20 at 19 17 35" src="https://user-images.githubusercontent.com/90396571/185756563-0008e6a7-9a6d-45b8-b403-31ee46b94ff7.png">

2022-08-20 16:38 UTC, frrenzy commented on src/index.html
>        <ul class="list">
этому списку не хватает класса, ай гесс. У него браузерный марджин в 16 пикселей, а должно быть:
мобилка - 20
десктоп - 30
+ в десктопном попапе он в строку
<img width="275" alt="Screenshot 2022-08-20 at 19 20 34" src="https://user-images.githubusercontent.com/90396571/185756722-4fc4e72d-14ca-47a1-a2d3-5ec2af3c2785.png">

2022-08-20 16:38 UTC, frrenzy commented on src/index.html
>        <ul class="list">
в карточках этот ноывй класс тоже добавь, пожалуйста

2022-08-20 16:38 UTC, frrenzy commented on src/blocks/courses/__skills-item/courses__skills-item.css
> +.courses__skills-item:last-of-type {
напишу тут. courses__skills-list надо направление флекса поменять, а то порядок не совпадает с макетом

2022-08-21 07:53 UTC, ivanfonin commented on src/blocks/popup/__container/popup__container.css
>    padding: 25px 22px;
Да, это из старого макета, похоже, было. Поправил на 15 и 10 соответственно в последнем комите.

2022-08-21 07:53 UTC, ivanfonin commented on src/blocks/popup/__container/popup__container.css
>      padding: 34px 36px 37px 36px;
Тоже поправил

2022-08-21 07:54 UTC, ivanfonin commented on src/blocks/popup/__close/popup__close.css
> +    right: 45px;
Поправил

2022-08-21 07:55 UTC, ivanfonin commented on src/blocks/popup/__buttons/popup__buttons.css
> +    align-items: center;
А это ты откуда взял? В попапе же нету кнопки смотреть все навыки. В попапе кнопки "Записаться" и "Закрыть" только.

2022-08-21 08:11 UTC, ivanfonin commented on src/blocks/courses/__skills-item/courses__skills-item.css
> +.courses__skills-item:last-of-type {
Вижу, там заполняется сначала первая колонка сверху вниз, потом вторая. В следующий коммит добавлю здесь column-count.

2022-08-21 08:22 UTC, ivanfonin commented on src/blocks/popup/__close/popup__close.css
> +  right: 0;
Поправил

2022-08-21 08:23 UTC, ivanfonin commented on src/index.html
>        <ul class="list">
Здесь не понял о чем ты говоришь. Уточни, пожалуйста.

2022-08-21 08:30 UTC, frrenzy commented on src/blocks/popup/__buttons/popup__buttons.css
> +    align-items: center;
Наверное, криво выразился. Мне кажется, на макете должна быть кнопка "закрыть" вместо кнопки "смотреть все навыки" - тут вопросов нет. 

А вот порядок у кнопок отличается от твоего

2022-08-21 08:36 UTC, ivanfonin commented on src/blocks/popup/__buttons/popup__buttons.css
> +    align-items: center;
Теперь я понял о чем ты. Я не раскрыл свою мысль. Я думаю, что из-за того, что дизайнер по ошибке перенёс кнопку "Смотреть все навыки", а не "Закрыть", поэтому он и поставил её не там где нужно. Не логично, что кнопка "Закрыть" идёт над кнопкой записаться, а не в самом конце после неё. Даже с точки зрения удобства использования. Если человек листает попап вниз, он не долистав до самой главной кнопки может пролистывая тыкнуть на "Закрыть" случайно. Логичнее кнопку "Закрыть" поставить в самом конце, но никак не над кнопкой "Записаться" –  это очень сомнительно. Повторюсь, в макете именно из-за того, что кнопку дизайнер перенёс не ту что нужно, поэтому так расположил, по аналогии с мобильной версией карточки.

2022-08-21 09:07 UTC, frrenzy requested changes
И по-моему я courses__tags задал марджин не 20 0, как надо, а 30 0. Поправь тоже, пожалуйста

2022-08-21 09:07 UTC, frrenzy commented on src/blocks/popup/_type/popup_type_partner.css
> +  padding: 15px;
сюда еще ширину надо calc(100% - 10px)
паддинг 10
<img width="330" alt="image" src="https://user-images.githubusercontent.com/90396571/185783654-52677177-bcf2-4d1b-83d3-3d5c74290dc1.png">

2022-08-21 09:07 UTC, frrenzy commented on src/blocks/popup/__figure/popup__figure.css
>    margin-bottom: 30px;
размеры фигуры не те 
<img width="330" alt="image" src="https://user-images.githubusercontent.com/90396571/185783529-04d548b7-218f-4e87-8be4-792ed6791ed4.png">

2022-08-21 09:07 UTC, frrenzy commented on src/index.html
>        <ul class="list">
- В разметке у списка, оборачивающего эти строчки, нет своего класса. У списка, следовательно, браузерный марджин в 16 пикселей. Нужно 20
<img width="993" alt="image" src="https://user-images.githubusercontent.com/90396571/185783901-43f20edb-f7e0-4461-88f8-8803dfe8018c.png">

- Также на десктопном попапе этот список должен встать в строку, для чего тоже нужно прописать стили в отдельном классе
<img width="273" alt="image" src="https://user-images.githubusercontent.com/90396571/185783824-49023ed5-54a0-4186-a869-bd640d1caa08.png">
<img width="589" alt="image" src="https://user-images.githubusercontent.com/90396571/185783832-13a27665-6f02-4514-853c-2d6fd4c717f3.png">

2022-08-21 09:08 UTC, frrenzy commented on src/blocks/popup/__buttons/popup__buttons.css
> +    align-items: center;
Согласен, логично

2022-08-21 10:00 UTC, ivanfonin commented on src/index.html
>        <ul class="list">
Теперь понял. Я на эти элементы, которые касаются курса вообще не смотрел, предполагал, что они должны автоматом стилизоваться по аналогии. Я обнулил у .list дефолтные margin – это надо делать по БЕМ, ничего дефолтного оставлять не нужно, потому что дефолтное в разных браузерах может быть разное. Соответственно это решило момент с отступами. В остальных блоках на сайте проверил, нигде ничего не поехало. Ну и выстроил в попапе этот список в строку на больших экранах, не заметил этого изначально.

2022-08-21 10:12 UTC, ivanfonin commented on src/blocks/popup/_type/popup_type_partner.css
> +  padding: 15px;
Паддинг у попапа партнёров подправил на 10px. А по ширине почему `calc(100% - 10px)`? У меня `calc(100% - 20px)`. Там же 10px слева и 10px справа – 20px.

2022-08-21 10:17 UTC, ivanfonin commented on src/blocks/popup/__figure/popup__figure.css
>    margin-bottom: 30px;
Поправил

2022-08-21 15:02 UTC, frrenzy commented on src/blocks/popup/_type/popup_type_partner.css
> +  padding: 15px;
так вот как раз этот попап 310 пикселей шириной, отступы по 5

2022-08-21 15:19 UTC, ivanfonin commented on src/blocks/popup/_type/popup_type_partner.css
> +  padding: 15px;
Я понять никак не мог о чем, потому что как по мне это по умолчанию выглядит как бред какой-то)) Попапы отличаются ширной на 10 пикселей. Даже в голову не могло придти. Я думал, что я опять не на те макеты смотрю) Поправил

2022-08-21 15:48 UTC, frrenzy submitted a review, later dismissed

2022-08-21 15:52 UTC, frrenzy approved these changes

2022-08-21 15:53 UTC, merged