Feature/popups js
frrenzy/balapanlar pull request #40
Opened 2022-08-20 15:44 UTC by ivanfonin

Добавил функционал открытия попапа с курсами. Я чего-то только сейчас заметил, что в разметке нет секции с партнёрами. Я почему-то думал, что её Кирилл верстает вместе с about. Поэтому тут пока только попап с курсами. Сейчас сверстаю партнёров и там добавлю попап партнёров тоже.

2022-08-21 17:28 UTC, ivanfonin commented
Добавил блок с партнёрами + функционал попапов партнёров. Надо поставить display: none; не адаптивным секциям на странице, чтобы посмотреть корректно.

2022-08-22 22:55 UTC, frrenzy requested changes
еще при мердже похоже что-то съехало, размеры картинки в попапе партнеров не совпадают с макетом ни на десктопе, ни на мобилке
<img width="233" alt="image" src="https://user-images.githubusercontent.com/90396571/186032587-ae3c4686-b187-4657-8f10-6706238eb9b8.png">

2022-08-22 22:55 UTC, frrenzy commented on src/components/PopupTypeCourse.js
> +    this._element.querySelector('.popup__buttons a').setAttribute('href', document.querySelector(`#course-id-${id}`).dataset.link);
за селекторы тегов по жопе дадут, мб что-то в духе .popup__buttons::not(.popup__close)

2022-08-22 22:55 UTC, frrenzy commented on src/components/PopupTypePartner.js
> +    this._element.querySelector('.popup__buttons a').setAttribute('href', document.querySelector(`#partner-id-${id}`).dataset.link);
то же самое, .popup__buttons .button

2022-08-22 22:55 UTC, frrenzy commented on src/components/PopupTypePartner.js
> +    let partnerContent = this._getPartnerContent(partnerId);
const

2022-08-22 22:55 UTC, frrenzy commented on src/components/PopupTypeCourse.js
> +    let courseContent = this._getCourseContent(courseId);
const

2022-08-22 22:55 UTC, frrenzy commented on src/index.html
> +        <img class="popup__img" src="<%=require('./images/partners/horizons.png')%>" alt="Логотип компании «ХимБио»">
alt от другой компании остался

2022-08-22 22:55 UTC, frrenzy commented on src/pages/index.js
> +  if (!evt.target.hasAttribute('data-course-id')) return;
мне кажется, эта проверка излишня. энивей потом менять будут, раз нам надо это все пока тупо захардкодить

2022-08-22 22:55 UTC, frrenzy commented on src/pages/index.js
> +    if (!evt.currentTarget.hasAttribute('data-partner-id')) return;
мне кажется, эта проверка излишня. энивей потом менять будут, раз нам надо это все пока тупо захардкодить

2022-08-22 22:55 UTC, frrenzy commented on src/pages/index.js
> +window.addEventListener('click', (evt) => {
чет вот это как-то совсем мимо. Лучше один раз при загрузке пробежаться и заселектить все кнопки, чем глобальный листенер
Array.from(document.querySelectorAll('[data-course-id]')).forEach(button => {
  button.addEventListener
});

2022-08-22 22:55 UTC, frrenzy commented on src/pages/index.js
> +document.querySelectorAll('.partners__button').forEach(button => {
чисто хороший тон - итерируемую коллекцию явно к массиву преобразовать
Array.from(document.querySelectorAll('.partners__button')).forEach

2022-08-22 22:55 UTC, frrenzy commented on src/index.html
> +              <img class="partners__img" src="<%=require('./images/partners/horizons.png')%>" alt="Логотип партнёра «Открывая горизонты»">
тут размеры тоже не те
<img width="540" alt="image" src="https://user-images.githubusercontent.com/90396571/186032770-f34d869e-1d3c-4b04-84e4-dd73ba13317a.png">

2022-08-23 16:36 UTC, frrenzy commented on src/components/Popup.js
> +      this.close();
тут return бы еще добавить

2022-08-27 13:16 UTC, ivanfonin commented on src/components/Popup.js
> +      this.close();
Вот тут не понял. Куда, с какой целью?

2022-08-27 13:19 UTC, ivanfonin commented on src/index.html
> +              <img class="partners__img" src="<%=require('./images/partners/horizons.png')%>" alt="Логотип партнёра «Открывая горизонты»">
Я вообще эти размеры не смотрел. Бывают макеты pixel perfect, где всё тютелька в тютельку. Но здесь как-то по умолчанию всё плюс/минус на глаз) К тому же с этими попапами такой момент, что партнёры же могут добавиться ещё, измениться и т. п., поэтому я их постарался в целом более или менее универсальными сделать, чтобы любой логотип, которые не вставь, норм смотрелся. Мне почему-то кажется, что применительно к этому макету вот так pixel perfect проверять лого никто не будет. Но если будут, то я поправлю этот момент лучше после ревью, а не сейчас)) потому что надеюсь, что не придётся этого делать))

2022-08-27 17:42 UTC, frrenzy commented on src/components/Popup.js
> +      this.close();
после клоуз. Смысл вторую проверку делать, если попап уже закрыли?

2022-08-27 21:23 UTC, frrenzy submitted a review, later dismissed

2022-08-27 21:27 UTC, frrenzy approved these changes

2022-08-27 21:27 UTC, merged