feature(about): add mobile version
frrenzy/balapanlar pull request #43
Opened 2022-08-20 21:42 UTC by KirillKamratov

2022-08-20 22:22 UTC, frrenzy reviewed
оставил коммнты по стилю/чистоте, что сразу в глаза бросается

2022-08-20 22:22 UTC, frrenzy commented on src/blocks/about/__features/about__features.css
> +@media screen and (max-width: 468px){
пробел после круглой скобки нужен

2022-08-20 22:22 UTC, frrenzy commented on src/blocks/about/__geotag/about__geotag.css
> +  background-size: 22px 22px;
это ж одно и то же, не?

2022-08-20 22:22 UTC, frrenzy commented on src/blocks/about/__image-container/_photo/about__image-container_photo_kids.css
> +    height: 255px;
сразу говорю, что тут процентики нужны будут

2022-08-20 22:22 UTC, frrenzy commented on src/blocks/about/__image-container/_photo/about__image-container_photo_school.css
> +    height: 255px;
и тут

2022-08-20 22:22 UTC, frrenzy commented on src/blocks/about/__image-title/about__image-title.css
> +    padding-left: 15.6px;
16 наверн? или надеемся на браузерное округление?

2022-08-20 22:22 UTC, frrenzy commented on src/blocks/about/__list/about__list.css
> +    margin: 0;
дублируется, удаляй

2022-08-20 22:22 UTC, frrenzy commented on src/blocks/about/__features/about__features.css
>    margin-left: 28px;
укажи тут явно 0 0 0 28, наверн

2022-08-20 22:22 UTC, frrenzy commented on src/blocks/about/__geotag/about__geotag.css
> +    width: 255px;
плохо, надо с % играться

2022-08-20 22:22 UTC, frrenzy commented on src/blocks/about/__geotag/about__geotag.css
> +    padding-left: 35px;
1 пиксель игрет роль? если нет, то удаляем отсюда, так как дубли

2022-08-20 22:22 UTC, frrenzy commented on src/blocks/about/__image-container/about__image-container.css
> +    background-size: cover;
а какой без медиаправила? укажи явно

2022-08-21 21:08 UTC, KirillKamratov commented on src/blocks/about/__features/about__features.css
> +@media screen and (max-width: 468px){
+

2022-08-21 21:12 UTC, KirillKamratov commented on src/blocks/about/__image-container/_photo/about__image-container_photo_kids.css
> +    height: 255px;
Пока оставляю, не разобрался.

2022-08-21 21:15 UTC, KirillKamratov commented on src/blocks/about/__image-container/_photo/about__image-container_photo_school.css
> +    height: 255px;
см. выше

2022-08-21 21:16 UTC, KirillKamratov commented on src/blocks/about/__geotag/about__geotag.css
> +  background-size: 22px 22px;
нет, в данном случае contain увеличивает картинку (прикладываю отличие
<img width="1552" alt="Снимок экрана 2022-08-18 в 19 13 42" src="https://user-images.githubusercontent.com/102192184/185811090-1d472c0f-bb97-488b-822b-06a74d5a288d.png">

2022-08-21 21:18 UTC, KirillKamratov commented on src/blocks/about/__image-title/about__image-title.css
> +    padding-left: 15.6px;
+

2022-08-21 21:19 UTC, KirillKamratov commented on src/blocks/about/__list/about__list.css
> +    margin: 0;
Имелся ввиду, видимо, марджин.
Его удалил

2022-08-21 21:20 UTC, KirillKamratov commented on src/blocks/about/__features/about__features.css
>    margin-left: 28px;
+

2022-08-21 21:25 UTC, KirillKamratov commented on src/blocks/about/__geotag/about__geotag.css
> +    width: 255px;
Попробовал, вроде вышло.

2022-08-21 21:25 UTC, KirillKamratov commented on src/blocks/about/__geotag/about__geotag.css
> +    padding-left: 35px;
играет, начинает прыгать и отличаться от pp.

2022-08-21 21:27 UTC, KirillKamratov commented on src/blocks/about/__image-container/about__image-container.css
> +    background-size: cover;
Указал без медиаправил, по сути, медиаправило тут не нужно

2022-08-26 14:47 UTC, frrenzy requested changes
комменты прошу читать внимательно, там есть что обсудить

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__geotag/about__geotag.css
> +  padding-left: 35px;
давай в 1 строку объединим

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__features/about__features.css
> +@media screen and (max-width: 744px) {
768 брат

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__geotag/about__geotag.css
> +@media screen and (max-width: 744px) {
768

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__geotag/about__geotag.css
> +@media screen and (max-width: 468px) {
425

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__image-container/_line/about__image-container_line_orange.css
> +@media screen and (max-width: 744px) {
768

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__image-container/_line/about__image-container_line_orange.css
> +@media screen and (max-width: 468px) {
425

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__image-container/_line/about__image-container_line_yellow.css
> +@media screen and (max-width: 744px) {
768

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__image-container/_line/about__image-container_line_yellow.css
> +@media screen and (max-width: 468px) {
425

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__image-container/about__image-container.css
> +@media screen and (max-width: 468px) {
425

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__image-subtitle/about__image-subtitle.css
> +@media screen and (max-width: 744px) {
768

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__image-subtitle/about__image-subtitle.css
> +@media screen and (max-width: 468px) {
425

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__image-title/about__image-title.css
> +@media screen and (max-width: 744px) {
768

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__image-title/about__image-title.css
> +@media screen and (max-width: 468px) {
425

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__subtitle/about__subtitle.css
> +@media screen and (max-width: 744px) {
768

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__subtitle/about__subtitle.css
> +@media screen and (max-width: 468px) {
425

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/list/__item/list__item.css
>    padding-left: 35px;
давай в 1 строку, и надо проверить, что не съехали курсы из-за этого

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/list/__item/list__item.css
> +  background-position: 0 0;
влей СВЕЖИЙ девелопмент к себе и проверь, что теперь не разъезжаются курсы из-за изменений в этом файле - он общий

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__title/about__title.css
> +@media screen and (max-width: 744px) {
768

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__title/about__title.css
> +@media screen and (max-width: 468px) {
425

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/about.css
> +@media screen and (max-width: 744px) {
768

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/about.css
> +@media screen and (max-width: 468px) {
425

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/header/__link/header__link.css
> -  font-family: 'Montserrat';
а бахни тут еще лайн хайт явно в 22

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/page/__element/_offset/page__element_offset_l.css
> +@media screen and (max-width: 468px) {
425

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/wrapper/wrapper.css
> +@media screen and (max-width: 744px) {
768

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/wrapper/wrapper.css
> +@media screen and (max-width: 468px) {
425

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/header/__link/header__link.css
> -  color: #000000;
тут явный цвет 252525 нужен, потому что это ссылки - браузер им подставляет синий по дефолту

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/about.css
> +    max-width: 744px;
595 наверн
![image](https://user-images.githubusercontent.com/90396571/186928621-fa622de5-b704-45fd-a457-fb604e3fbe08.png)

вот так выглядит, если поменять на 595
![image](https://user-images.githubusercontent.com/90396571/186928938-29d2e0e6-d1e8-49b1-9d1a-4163af9e98f0.png)

я бы вообще наверн просто паддинги у wrapper боковые менял, а этой секции поставил ширину 100% и в хуй не дул

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__title/about__title.css
> +    font-size: 48px;
тут ширины блоку текста не хватает (скрин с уже пофиклешшной по ширине секцией)
![image](https://user-images.githubusercontent.com/90396571/186929993-6507627b-f08c-43e5-934c-26e25394add9.png)

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__image-container/about__image-container.css
> +  .about__image-container {
ему надо свой бордер-радиус на планшете задать, 40
![image](https://user-images.githubusercontent.com/90396571/186930607-9d6dc1d3-f39b-499f-a2f7-5ab3f9cb3cc4.png)

+ картинка снизу слева за угол вылезает, присмотрись

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/wrapper/wrapper.css
> +    padding-top: 30px;
на мобилке у него нет скруглений
![image](https://user-images.githubusercontent.com/90396571/186931162-d9ef0a49-cbf6-4422-9bcf-4d8c3cc64cc2.png)

2022-08-26 14:47 UTC, frrenzy commented on src/blocks/about/__features/about__features.css
> +
не хватает смены отступа снизу на 60 на мобилке
![image](https://user-images.githubusercontent.com/90396571/186931464-b2ec9033-cb44-41b3-b3b5-bc35afe20a33.png)

2022-08-26 16:53 UTC, KirillKamratov commented on src/blocks/about/__image-container/_photo/about__image-container_photo_kids.css
> +    height: 255px;
+

2022-08-26 16:54 UTC, KirillKamratov commented on src/blocks/about/__image-container/_photo/about__image-container_photo_school.css
> +    height: 255px;
+

2022-08-26 16:56 UTC, KirillKamratov commented on src/blocks/about/__geotag/about__geotag.css
> +  padding-left: 35px;
+

2022-08-26 17:01 UTC, KirillKamratov commented on src/blocks/about/__features/about__features.css
> +@media screen and (max-width: 744px) {
+

2022-08-26 17:01 UTC, KirillKamratov commented on src/blocks/about/__geotag/about__geotag.css
> +@media screen and (max-width: 744px) {
+

2022-08-26 17:01 UTC, KirillKamratov commented on src/blocks/about/__geotag/about__geotag.css
> +@media screen and (max-width: 468px) {
+

2022-08-26 17:02 UTC, KirillKamratov commented on src/blocks/about/__image-container/_line/about__image-container_line_orange.css
> +@media screen and (max-width: 744px) {
+

2022-08-26 17:02 UTC, KirillKamratov commented on src/blocks/about/__image-container/_line/about__image-container_line_orange.css
> +@media screen and (max-width: 468px) {
+

2022-08-26 17:02 UTC, KirillKamratov commented on src/blocks/about/__image-container/_line/about__image-container_line_yellow.css
> +@media screen and (max-width: 744px) {
+

2022-08-26 17:02 UTC, KirillKamratov commented on src/blocks/about/__image-container/_line/about__image-container_line_yellow.css
> +@media screen and (max-width: 468px) {
+

2022-08-26 17:02 UTC, KirillKamratov commented on src/blocks/about/__image-container/about__image-container.css
> +@media screen and (max-width: 468px) {
+

2022-08-26 17:02 UTC, KirillKamratov commented on src/blocks/about/__image-subtitle/about__image-subtitle.css
> +@media screen and (max-width: 744px) {
+

2022-08-26 17:02 UTC, KirillKamratov commented on src/blocks/about/__image-subtitle/about__image-subtitle.css
> +@media screen and (max-width: 468px) {
+

2022-08-26 17:02 UTC, KirillKamratov commented on src/blocks/about/__image-title/about__image-title.css
> +@media screen and (max-width: 744px) {
+

2022-08-26 17:02 UTC, KirillKamratov commented on src/blocks/about/__image-title/about__image-title.css
> +@media screen and (max-width: 468px) {
+

2022-08-26 17:03 UTC, KirillKamratov commented on src/blocks/about/__subtitle/about__subtitle.css
> +@media screen and (max-width: 744px) {
+

2022-08-26 17:03 UTC, KirillKamratov commented on src/blocks/about/__subtitle/about__subtitle.css
> +@media screen and (max-width: 468px) {
+

2022-08-26 18:31 UTC, KirillKamratov commented on src/blocks/list/__item/list__item.css
>    padding-left: 35px;
+

2022-08-26 18:31 UTC, KirillKamratov commented on src/blocks/about/__title/about__title.css
> +@media screen and (max-width: 744px) {
+

2022-08-26 18:31 UTC, KirillKamratov commented on src/blocks/about/__title/about__title.css
> +@media screen and (max-width: 468px) {
+

2022-08-26 18:31 UTC, KirillKamratov commented on src/blocks/about/about.css
> +@media screen and (max-width: 744px) {
+

2022-08-26 18:31 UTC, KirillKamratov commented on src/blocks/about/about.css
> +@media screen and (max-width: 468px) {
+

2022-08-26 18:33 UTC, KirillKamratov commented on src/blocks/header/__link/header__link.css
> -  font-family: 'Montserrat';
Уже было

2022-08-26 18:33 UTC, KirillKamratov commented on src/blocks/page/__element/_offset/page__element_offset_l.css
> +@media screen and (max-width: 468px) {
+

2022-08-26 18:33 UTC, KirillKamratov commented on src/blocks/wrapper/wrapper.css
> +@media screen and (max-width: 744px) {
+

2022-08-26 18:33 UTC, KirillKamratov commented on src/blocks/wrapper/wrapper.css
> +@media screen and (max-width: 468px) {
+

2022-08-26 18:34 UTC, KirillKamratov commented on src/blocks/header/__link/header__link.css
> -  color: #000000;
+

2022-08-26 18:38 UTC, KirillKamratov commented on src/blocks/about/__title/about__title.css
> +    font-size: 48px;
+

2022-08-26 18:47 UTC, KirillKamratov commented on src/blocks/about/__features/about__features.css
> +
+

2022-08-26 19:03 UTC, KirillKamratov commented on src/blocks/about/__image-container/about__image-container.css
> +  .about__image-container {
+

2022-08-26 21:45 UTC, KirillKamratov commented on src/blocks/about/about.css
> +    max-width: 744px;
+

2022-08-27 00:42 UTC, frrenzy requested changes
главное - разъезжается список с галками, на курсах тем более, ширина секции плавает и получается так себе

2022-08-27 00:42 UTC, frrenzy commented on src/blocks/about/__feature/about__feature.css
> +    margin-left: 1px;
вот эту строчку убери - она подтянется из верхнего правила

2022-08-27 00:42 UTC, frrenzy commented on src/blocks/about/__feature/about__feature.css
> +
- за отрицательные марджины по жопе дадут точно
- оверолл мне кажется ты перемудрил, стало разъезжаться немного
![image](https://user-images.githubusercontent.com/90396571/187006692-187f6f06-8b89-4d26-8ade-db6c5b045f23.png)

2022-08-27 00:42 UTC, frrenzy commented on src/blocks/about/__features/about__features.css
> +  }
сюда можно добавить отмену max-width, мне кажется, так сипатичнее

2022-08-27 00:42 UTC, frrenzy commented on src/blocks/about/__image-subtitle/about__image-subtitle.css
> +    width: 544px;
![image](https://user-images.githubusercontent.com/90396571/187006942-02195dce-448e-45fd-af3d-58fcb4428550.png)

хватит поменять на макс, ай гесс. в нижнем правиле так же

2022-08-27 00:42 UTC, frrenzy commented on src/blocks/about/__image-title/about__image-title.css
> +    font-size: 40px;
чет со шрифтом/линией надо делать
и чекни как картинка флексит
ширина 500
![image](https://user-images.githubusercontent.com/90396571/187007150-692f0bbd-d4bb-49e4-bb6e-03b9b11f9178.png)

2022-08-27 00:42 UTC, frrenzy commented on src/blocks/wrapper/wrapper.css
> +
паддинги наверн и на десктопе нужны, и в целом оцени секцию. ширина 790
![image](https://user-images.githubusercontent.com/90396571/187007208-31b2c1e8-b2b1-461a-9ebe-d55075e529e4.png)
![image](https://user-images.githubusercontent.com/90396571/187007224-8bf48cda-afec-42e0-868e-222560a2c8a8.png)

2022-08-27 00:42 UTC, frrenzy commented on src/blocks/about/__subtitle/about__subtitle.css
> +
скорее всего пофиксится фиксом рэппера, но на всякий  скрин 
![image](https://user-images.githubusercontent.com/90396571/187007260-795eda0e-6406-439f-87c2-e49f7da4c8b4.png)

2022-08-27 00:42 UTC, frrenzy commented on src/blocks/about/about.css
> +    scroll-margin-top: 16px;
больше надо 
![image](https://user-images.githubusercontent.com/90396571/187007284-c1ec67ac-6f1c-4836-9db5-6226727b7b88.png)

2022-08-27 00:42 UTC, frrenzy commented on src/blocks/list/__item/list__item.css
> +  background-position: 0 0;
таки начало разъезжаться
![image](https://user-images.githubusercontent.com/90396571/187007423-3650a1ce-77e4-4e58-88a2-fa1f0d1bd0ce.png)

2022-08-27 17:20 UTC, KirillKamratov commented on src/blocks/about/__feature/about__feature.css
> +    margin-left: 1px;
+

2022-08-27 17:44 UTC, KirillKamratov commented on src/blocks/about/__feature/about__feature.css
> +
+

2022-08-27 17:45 UTC, KirillKamratov commented on src/blocks/about/__image-subtitle/about__image-subtitle.css
> +    width: 544px;
+

2022-08-27 17:52 UTC, KirillKamratov commented on src/blocks/wrapper/wrapper.css
> +
Gap сделал, но картинки все равно всратенько выглядят

2022-08-27 18:08 UTC, KirillKamratov commented on src/blocks/about/__subtitle/about__subtitle.css
> +
не пофиксилось, задал макс вид

2022-08-27 18:09 UTC, KirillKamratov commented on src/blocks/about/about.css
> +    scroll-margin-top: 16px;
+

2022-08-28 02:41 UTC, frrenzy approved these changes

2022-08-28 02:41 UTC, merged