Feature/burger menu
frrenzy/balapanlar pull request #47
Opened 2022-08-24 06:10 UTC by bronik04

Сделал бургер меню на разрешении ниже 1024
добавил выпадашку и анимацию крестика

2022-08-24 10:59 UTC, frrenzy requested changes
треды

2022-08-24 10:59 UTC, frrenzy commented on src/blocks/header/__burger/header__burger.css
> +@media (max-width: 1024px) {
тут 744 должно быть
<img width="309" alt="image" src="https://user-images.githubusercontent.com/90396571/186399820-ab59a42f-5ec8-4e66-839d-0c8223cf26c7.png">

2022-08-24 10:59 UTC, frrenzy commented on src/blocks/header/__burger/header__burger.css
> +  .header__burger.header__nav_opened::before {
тут наверн другой класс должен быть, потому что получается так
<img width="364" alt="image" src="https://user-images.githubusercontent.com/90396571/186401497-6e6d3735-c292-46e3-ad8e-d1e6d059c1d8.png">
Элемент  - бургер, а модификатор нава.

Так же избавит от необходимости двойного селектора

2022-08-24 10:59 UTC, frrenzy commented on src/blocks/header/__burger/header__burger.css
> +  .header__burger.header__nav_opened::after {
тут наверн другой класс должен быть, потому что получается так
<img width="364" alt="image" src="https://user-images.githubusercontent.com/90396571/186401497-6e6d3735-c292-46e3-ad8e-d1e6d059c1d8.png">
Элемент  - бургер, а модификатор нава.

Так же избавит от необходимости двойного селектора

2022-08-24 10:59 UTC, frrenzy commented on src/blocks/header/__menu/header__menu.css
> +@media (max-width: 1024px) {
744

2022-08-24 10:59 UTC, frrenzy commented on src/blocks/header/__nav/_opened/header__nav_opened.css
> +  /* display: flex; */
давай комменты подчистим

2022-08-24 10:59 UTC, frrenzy commented on src/blocks/header/__nav/header__nav.css
> +@media (max-width: 1024px) {
744

2022-08-24 10:59 UTC, frrenzy commented on src/blocks/header/header.css
> +@media (max-width: 1024px) {
744

2022-08-24 10:59 UTC, frrenzy commented on src/blocks/logo/__mob/logo__mob.css
> +@media (max-width: 1024px) {
744

2022-08-24 10:59 UTC, frrenzy commented on src/blocks/logo/__mob/logo__mob.css
> +  .logo__mob {
давай все-таки  logo__mobile, а то как-то как будто буквы платные

2022-08-24 10:59 UTC, frrenzy commented on src/pages/index.js
> +const navigation = document.querySelector(".header__nav");
давай тут одинарные кавычки, как везде

2022-08-24 10:59 UTC, frrenzy commented on src/pages/index.js
> +  burgerButton.classList.toggle('header__nav_opened');
и тут тоже не забудь на новый класс поменять

2022-08-24 15:23 UTC, bronik04 commented on src/blocks/header/__nav/header__nav.css
> +@media (max-width: 1024px) {
Готово

2022-08-24 15:23 UTC, bronik04 commented on src/blocks/header/header.css
> +@media (max-width: 1024px) {
Готово

2022-08-24 15:23 UTC, bronik04 commented on src/blocks/logo/__mob/logo__mob.css
> +@media (max-width: 1024px) {
Готово

2022-08-24 15:26 UTC, bronik04 commented on src/blocks/logo/__mob/logo__mob.css
> +  .logo__mob {
Готово

2022-08-24 15:27 UTC, bronik04 commented on src/pages/index.js
> +const navigation = document.querySelector(".header__nav");
Готово

2022-08-24 15:28 UTC, bronik04 commented on src/blocks/header/__nav/_opened/header__nav_opened.css
> +  /* display: flex; */
Готово

2022-08-24 15:28 UTC, bronik04 commented on src/blocks/header/__menu/header__menu.css
> +@media (max-width: 1024px) {
Готово

2022-08-24 15:29 UTC, bronik04 commented on src/blocks/header/__burger/header__burger.css
> +@media (max-width: 1024px) {
Готово

2022-08-24 15:37 UTC, bronik04 commented on src/blocks/header/__burger/header__burger.css
> +  .header__burger.header__nav_opened::before {
Готово

2022-08-24 15:37 UTC, bronik04 commented on src/pages/index.js
> +  burgerButton.classList.toggle('header__nav_opened');
готово

2022-08-25 19:27 UTC, frrenzy submitted a review, later dismissed
LGTM

2022-08-25 19:30 UTC, frrenzy approved these changes

2022-08-25 19:30 UTC, merged