Refactor/intro
frrenzy/balapanlar pull request #51
Opened 2022-08-24 19:27 UTC by anastasiian3

Брейкпоинты старалась максимально брать те, о которых говорили, если стоят не те - ломаются элементы, если до них терпеть. При скролле/без скролла на планшетке исправлен фон, под мобилу не стала заморачиваться, там его не видно под фиолетовой плашкой. Долго подбирала промежуточные значения, потому что аспект рейшо упарывается. По пп все супер.

2022-08-26 14:13 UTC, frrenzy requested changes

2022-08-26 14:13 UTC, frrenzy commented on src/blocks/intro/__bar/intro__bar.css
> +    position: relative;
а зачем тут релатив? он же ни на что не влияет - сдвигов нет, абсолютно спозиционированных детей тоже нет

2022-08-26 14:13 UTC, frrenzy commented on src/blocks/intro/__bar/intro__bar.css
> +    bottom: 0;
ну и эта строка даже в релатив ни на что не влияет

2022-08-26 14:13 UTC, frrenzy commented on src/blocks/intro/__bar/intro__bar.css
> +    border-radius: 40px;
в целом эту штуку докрутить надо 
![image](https://user-images.githubusercontent.com/90396571/186919597-e42d1acd-68b6-4db7-8d12-cb079e57c1d0.png)

2022-08-26 14:13 UTC, frrenzy commented on src/blocks/intro/__bar/intro__bar.css
> +    border-radius: 40px;
мб просто флекса хватит с колонкой, на макете по 30 от верха и низа и по 15 между элементами

2022-08-27 00:50 UTC, frrenzy commented on src/blocks/intro/__bar/intro__bar.css
> +    max-width: 95%;
не оч понял, почему не 100%

2022-08-27 08:09 UTC, anastasiian3 commented on src/blocks/intro/__bar/intro__bar.css
> +    position: relative;
а это я забыла убрать, исправила

2022-08-27 08:10 UTC, anastasiian3 commented on src/blocks/intro/__bar/intro__bar.css
> +    border-radius: 40px;
![image](https://user-images.githubusercontent.com/102759284/187021411-4f7ae1bb-9c82-4f34-a584-a4df7cdb5e58.png)
ох уж этот дизайнер

2022-08-27 09:29 UTC, anastasiian3 commented on src/blocks/intro/__bar/intro__bar.css
> +    max-width: 95%;
потому что отображение как на мобилке начинается с 500, до этого еще все смотрится как на планшете
![image](https://user-images.githubusercontent.com/102759284/187024241-43e5fcf7-4abd-4d12-b3a5-d98b18bf5834.png)
это вот плюс-минус 510
![image](https://user-images.githubusercontent.com/102759284/187024250-c43e7ad2-9c60-4629-987b-0a2092891918.png)
около 490

2022-08-27 11:36 UTC, frrenzy approved these changes
lgtm

2022-08-27 11:37 UTC, merged