Hotfix/about
frrenzy/balapanlar pull request #68
Opened 2022-08-31 19:12 UTC by KirillKamratov

Remove wrapper

2022-08-31 23:20 UTC, frrenzy requested changes

2022-08-31 23:20 UTC, frrenzy commented on src/blocks/about/about.css
> +    padding-bottom: 80px;
тут радиусы границы 50

2022-08-31 23:20 UTC, frrenzy commented on src/blocks/about/about.css
> +  scroll-margin-top: 75px;
тут 75, а снизу 80 и 72. разница важна?

2022-08-31 23:20 UTC, frrenzy commented on src/index.html
> -    <div class="wrapper rounded column">
закрывающий тег не удалил

2022-08-31 23:20 UTC, frrenzy commented on src/blocks/partners/partners.css
> +  padding: 80px calc(50% - 443px) 160px;
- это шо за монстр по горизонтали? особенно если учесть, что кусок стилей про мобильные девайсы
- снизу 50, насколько я вижу
- сверху 30

2022-08-31 23:20 UTC, frrenzy commented on src/blocks/partners/partners.css
> +  box-sizing: content-box;
это дефолтное значение, зачем писать?

2022-08-31 23:20 UTC, frrenzy commented on src/blocks/partners/partners.css
> +  align-items: center;
это же не флекс- и не грид-контейнер, зачем тут это свойство?

2022-08-31 23:20 UTC, frrenzy commented on src/blocks/partners/partners.css
> +    border-bottom-left-radius: 60px;
тут 50, 60 от 768 и вверх

2022-08-31 23:20 UTC, frrenzy commented on src/blocks/partners/__heading/partners__heading.css
> +  padding-left: 15px;
- объедини в 1 строчку
- и наверн в медиа тогда надо обнулять его?

2022-08-31 23:20 UTC, frrenzy commented on src/blocks/about/about.css
> +    padding: 30px 15px 0;
я бы 30 15 поставил, и 30 удалил из верхнего паддинга партнеров

2022-08-31 23:20 UTC, frrenzy commented on src/blocks/about/about.css
> +  padding: 120px 120px 80px;
нижний 100

2022-08-31 23:21 UTC, frrenzy commented on src/blocks/partners/__heading/partners__heading.css
> +  padding-left: 15px;
и возможно я в десктопных стилях нижний паддинг пропустил, проверь пж

2022-09-01 19:52 UTC, KirillKamratov commented on src/index.html
> -    <div class="wrapper rounded column">
+

2022-09-01 19:53 UTC, KirillKamratov commented on src/blocks/partners/partners.css
> +  box-sizing: content-box;
+

2022-09-01 19:54 UTC, KirillKamratov commented on src/blocks/partners/partners.css
> +  align-items: center;
+

2022-09-01 19:55 UTC, KirillKamratov commented on src/blocks/partners/partners.css
> +  align-items: center;
+

2022-09-01 19:55 UTC, KirillKamratov commented on src/blocks/about/about.css
> +  padding: 120px 120px 80px;
+

2022-09-01 19:55 UTC, KirillKamratov commented on src/blocks/partners/partners.css
> +  box-sizing: content-box;
+

2022-09-01 19:55 UTC, KirillKamratov commented on src/blocks/partners/partners.css
> +  align-items: center;
+

2022-09-01 19:57 UTC, KirillKamratov commented on src/blocks/about/about.css
> +    padding: 30px 15px 0;
+

2022-09-01 19:59 UTC, KirillKamratov commented on src/blocks/about/about.css
> +  padding: 120px 120px 80px;
+

2022-09-01 20:13 UTC, KirillKamratov commented on src/blocks/about/about.css
> +    padding-bottom: 80px;
+

2022-09-01 20:18 UTC, KirillKamratov commented on src/blocks/about/about.css
> +  scroll-margin-top: 75px;
ВАжна, пофиксил

2022-09-01 20:19 UTC, KirillKamratov commented on src/blocks/partners/partners.css
> +  padding: 80px calc(50% - 443px) 160px;
+

2022-09-01 20:19 UTC, KirillKamratov commented on src/blocks/partners/partners.css
> +  box-sizing: content-box;
+

2022-09-01 20:21 UTC, KirillKamratov commented on src/blocks/partners/__heading/partners__heading.css
> +  padding-left: 15px;
+

2022-09-01 21:34 UTC, KirillKamratov commented on src/blocks/partners/partners.css
> +    border-bottom-left-radius: 60px;
+

2022-09-02 02:15 UTC, frrenzy approved these changes

2022-09-02 02:15 UTC, merged